name = "Jean C. Páez R."
rol = "Flutter Developer"
email = "paezdev@gmail.com"
phone = "+57 311 416 6991"
birthday = "May 23, 1983"
location = "Caucasia - Antioquia, Colombia"
avatar = "./config/assets/avatars/avatar-1.png"
username = "paez-dev" # <-- github user name
googlemaps = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d31609.567483801915!2d-75.23683953246642!3d7.97868972590491!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e5b6f03c070dcf1%3A0x5d4d101c959d9c74!2sCaucasia%2C%20Antioquia%2C%20Colombia!5e0!3m2!1sen!2sbd!4v1687410386481!5m2!1sen!2sbd" 
presentation = """
I'm a trainee software developer, from Colombia, I'm studying Dart and flutter and in web development, I'm taking the route to be a backend. I enjoy solving complex problems.

My job is to build websites and mobile applications so that it is functional and easy to use, but at the same time attractive. In addition, I give it a personal touch and make sure my work is eye-catching and user-friendly. My goal, apart from being functional, is to provide an excellent user experience.
"""