HEADER:
  label: "Blog"

POSTS:
  - title: "How to Sort Arrays in Swift"
    category: "Swift"
    subtitle: "Learn how to efficiently sort arrays in Swift using built-in methods like sorted() and sort(), custom closures, and the Comparable protocol."
    published: "2025-03-30"
    image: "https://raw.githubusercontent.com/ivansaul/blog/master/docs/assets/images/swift-how-to-sort-arrays-in-swift-banner.avif"
    url: "https://ivansaul.github.io/blog/swift/continued-learning/how-to-sort-arrays-in-swift"

  - title: "How to get a sublist from a list in Swift"
    category: "Swift"
    subtitle: "Learn how to extract sublists from arrays in Swift using various methods, including slicing, prefix, suffix, drop, filter, and stride. Avoid common pitfalls and ensure safe sublist extraction."
    published: "2025-03-11"
    image: "https://raw.githubusercontent.com/ivansaul/blog/master/docs/assets/images/swift-how-to-get-a-sublist-from-a-list-in-swift-banner.avif"
    url: "https://ivansaul.github.io/blog/swift/continued-learning/how-to-get-a-sublist-from-a-list-in-swift"

  - title: "SwiftUI Animations"
    category: "SwiftUI"
    subtitle: "Discover the power of SwiftUI animations and learn how to create dynamic and engaging user interfaces."
    published: "2025-02-22"
    image: "https://raw.githubusercontent.com/ivansaul/blog/master/docs/assets/images/swiftui-animations-banner.avif"
    url: "https://ivansaul.github.io/blog/swiftui/continued-learning/swiftui-animations"

  - title: "Teldrive Free Unlimited Cloud Storage"
    category: "Apps"
    subtitle: "How to get unlimited free cloud storage. Teldrive is a free and open-source alternative to Google Drive, Dropbox, and OneDrive. It is a self-hosted file storage system that allows us to store our files in the cloud and share them with others."
    published: "2024-12-05"
    image: "https://raw.githubusercontent.com/ivansaul/blog/master/docs/assets/images/teldrive-free-unlimited-cloud-storage-banner.avif"
    url: "https://ivansaul.github.io/blog/apps/drive/teldrive-free-unlimited-cloud-storage"

  - title: "SwiftUI Text"
    category: "SwiftUI"
    subtitle: "Text views are one of the most fundamental and frequently used components in any SwiftUI user interface. They enable us to display text in our apps, serving as labels, titles, descriptions, and much more."
    published: "2024-12-02"
    image: "https://raw.githubusercontent.com/ivansaul/blog/master/docs/assets/images/swiftui-text-banner.avif"
    url: "https://ivansaul.github.io/blog/swiftui/getting-started/swiftui-text"

  - title: "Xcode How to Customize File Headers"
    category: "Apps"
    subtitle: "Default headers in Xcode are useful, but not always enough. Learn how to add personalized details like repository links, version numbers, or any other information you need."
    published: "2024-12-02"
    image: "https://raw.githubusercontent.com/ivansaul/blog/master/docs/assets/images/xcode-how-to-customize-file-headers-banner.avif"
    url: "https://ivansaul.github.io/blog/apps/xcode/xcode-how-to-customize-file-headers"

  - title: "Extensions in Swift"
    category: "Swift"
    subtitle: "Discover the power of Swift extensions to enhance existing types with new methods, properties, and initializers. Learn how to customize and expand your code effortlessly while keeping it clean and modular."
    published: "2024-11-30"
    image: "https://raw.githubusercontent.com/ivansaul/blog/master/docs/assets/images/swift-extensions-in-swift-banner.avif"
    url: "https://ivansaul.github.io/blog/swift/continued-learning/extensions-in-swift"

  - title: "How to Add Custom Fonts in SwiftUI"
    category: "SwiftUI"
    subtitle: "Transform the look of your SwiftUI app by adding custom fonts! This step-by-step guide will show you how to easily integrate and use your favorite fonts, giving your app a unique and stylish edge."
    published: "2024-11-30"
    image: "https://raw.githubusercontent.com/ivansaul/blog/master/docs/assets/images/swiftui-how-to-add-custom-fonts-in-swiftui-banner.avif"
    url: "https://ivansaul.github.io/blog/swiftui/continued-learning/how-to-add-custom-fonts-in-swiftui"

  - title: "Opening Ports on Oracle Cloud Instances"
    category: "Linux"
    subtitle: "Learn how to open ports on an Oracle Cloud Instance to allow incoming traffic on specific ports."
    published: "2024-11-30"
    image: "https://raw.githubusercontent.com/ivansaul/blog/master/docs/assets/images/open-ports-on-oracle-cloud-banner.avif"
    url: "https://ivansaul.github.io/blog/linux/guides/opening-ports-on-oracle-cloud-instances"

