[[post]]
category = "Python"
title = "Python environment variables"
subtitle = "Interacting with environment variables in Python for app configuration and secrets."
datetime = "2023-01-05"
image = "https://i.imgur.com/CgUGNaS.png"
url = "https://ivansaul.github.io/wiki/Programming/Python/General/Python-environment-variables"

[[post]]
category = "Dart"
title = "Dart Record type"
subtitle = "Exploring Dart Records and their syntax for returning multiple values."
datetime = "2024-02-19"
image = "https://i.imgur.com/IJM5GNe.jpg"
url = "https://ivansaul.github.io/wiki/Programming/Dart/Records"

[[post]]
category = "Flutter"
title = "Flutter Custom Icons"
subtitle = "How to Add Custom Icons to Your Flutter Application."
datetime = "2024-02-19"
image = "https://i.imgur.com/JH1wCJE.jpg"
url = "https://ivansaul.github.io/wiki/Programming/Flutter/General/Custom-Icons"

[[post]]
category = "Dart"
title = "Dart Useful Methods"
subtitle = "A collection of useful Dart methods with examples."
datetime = "2024-03-01"
image = "https://i.imgur.com/ry6DbkM.png"
url = "https://ivansaul.github.io/wiki/Programming/Dart/Useful-Methods"
