HEADER:
  label: "Portfolio"

PROJECTS:
  - title: "Flutter Cinemapedia App"
    category: "Mobile development"
    image: "https://raw.githubusercontent.com/ivansaul/demos/master/images/flutter-cinemapedia-banner.webp"
    url: "https://github.com/ivansaul/flutter_cinemapedia_app#screenshots"

  - title: "Flutter Coffee Shop App"
    category: "Mobile development"
    image: "https://raw.githubusercontent.com/ivansaul/demos/master/images/flutter-coffee-shop-banner.webp"
    url: "https://github.com/ivansaul/flutter_coffee_shop_app#screenshots"

  - title: "Flutter Todo App"
    category: "Mobile development"
    image: "https://raw.githubusercontent.com/ivansaul/demos/master/images/flutter-todo-banner.webp"
    url: "https://github.com/ivansaul/flutter_todo_app#screenshots"

  - title: "Flutter Travel News App"
    category: "Mobile development"
    image: "https://raw.githubusercontent.com/ivansaul/demos/master/images/flutter-travel-news-banner.webp"
    url: "https://github.com/ivansaul/flutter_travel_news_app#screenshots"

  - title: "Codigo Facilito Downloader"
    category: "Python Scripting"
    image: "https://raw.githubusercontent.com/ivansaul/demos/master/images/codigo-facilito-downloader-banner.webp"
    url: "https://github.com/ivansaul/codigo_facilito_downloader"

  - title: "Personal Portfolio"
    category: "Web development"
    image: "https://raw.githubusercontent.com/ivansaul/demos/master/images/personal-portfolio-banner.webp"
    url: "https://github.com/ivansaul/personal-portfolio"

