############## Education config #################
#################################################
[[education]]
title = "Universidad Nacional de Ingeniería - UNI"
timeline = "2013 — 2018"
description = "Facultad de Ingenieria Geológica, Minas y Metalurgica"

[[education]]
title = "CEPS - UNI"
timeline = "2015 — 2016"
description = "Programacion Orientada a Objetos con Python y C++"

[[education]]
title = "Bootcamp Python Web Scraping - Udemy"
timeline = "2016 — 2017"
description = "Completé un bootcamp especializado en técnicas de Web Scraping, Web Crawling y Web Automation. Durante el curso, adquirí habilidades en la extracción de datos de sitios web, la navegación automatizada y el análisis de contenido web utilizando Python, Selenium y BeautifulSoup."

[[education]]
title = "Flutter Móvil - Udemy"
timeline = "Dic 2022 - Feb 2023"
description = "Durante el curso adquirí conocimientos fundamentales sobre la arquitectura de Flutter, el diseño de interfaces de usuario y la implementación de funcionalidades interactivas para iOS y Android hasta su despliegue en las tiendas."

[[education]]
title = "Flutter State Managment Riverpod/Bloc"
timeline = "Mar 2023 - En Curso"
description = "Estoy dedicando tiempo y esfuerzo a estudiar y desarrollar habilidades en el manejo de estados utilizando las bibliotecas Riverpod y BloC en el contexto de Flutter."


############# Experience config #################
#################################################
[[experience]]
title = "Planeamiento Minero - Buenaventura"
timeline = "Nov 2018 — Ago 2019"
description = "Desarrollé y creé aplicaciones informáticas con Python en el software minero Minesight para automatizar el manejo de bloques. Mejora de la eficiencia y precisión en la planificación minera, reducción de tiempos de procesamiento y minimización de errores humanos."

[[experience]]
title = "Planeamiento y Productividad - CIA Minera Volcan"
timeline = "Set 2019 — Set 2021"
description = "Durante mi tiempo en la empresa, desempeñé un papel clave en la reducción de costes mediante la implementación de medidas efectivas para disminuir el consumo de explosivos en las operaciones mineras. Mi enfoque se centró en la optimización de los procesos de voladura, aplicando técnicas innovadoras y estrategias eficientes."

[[experience]]
title = "Supervisor Operaciones Mina - Casapalca"
timeline = "Oct 2021 — Ene 2023"
description = "En mi rol como Supervisor de Operaciones en el interior mina, tuve la responsabilidad de liderar y coordinar las actividades diarias del equipo de trabajadores bajo mi supervisión. Trabajé en estrecha colaboración con el personal de producción para garantizar un funcionamiento eficiente y seguro de las operaciones mineras."


############## Skills config ####################
#################################################
[skills] 
title = "My Skills"
enabled = true
show_bar = false
show_value = false

[[skill]]
title = "Flutter"
value = "60%"

[[skill]]
title = "Python"
value = "70%"

[[skill]]
title = "Git"
value = "65%"

[[skill]]
title = "Dart"
value = "60%"

[[skill]]
title = "HTML/CSS"
value = "60%"

[[skill]]
title = "Figma"
value = "60%"

[[skill]]
title = "Adobe Illustrator"
value = "70%"


############## Language config ##################
#################################################
[languages]
title = "Languages"
enabled = true
show_bar = false
show_value = false

[[language]]
title = "Ingles"
value = "60%"

[[language]]
title = "Quechua"
value = "80%"