# https://ionic.io/ionicons
# <ion-icon name="logo-[[name]]"></ion-icon>
# name = "https://example.com/"

github = "https://github.com/ivansaul"
linkedin = "https://www.linkedin.com/in/ivansaul/"
#facebook = "https://facebook.com/"
#twitter = "https://twitter.com/"
#instagram = "https://instagram.com/"
#dribbble = "https://dribbble.com/"
# figma = "figma.com/"
# youtube = "https://youtube.com/"
# reddit = "https://www.reddit.com/"
# discord = "https://discord.com/"
# pinterest = "https://www.pinterest.com/"